# Item.create(name: "ball", size: 8, picture: "/items/ball.png")
# Item.create(name: "bear", size: 8, picture: "/items/bear.png")
# Item.create(name: "cube", size: 8, picture: "/items/cube.png")
# Item.create(name: "egame", size: 8, picture: "/items/egame.png")
# Item.create(name: "robot", size: 8, picture: "/items/robot.png")
# Item.create(name: "xylophone", size: 8, picture: "/items/xylophone.png")
Ingredient.create(name: "bottle", picture: "/ingredients/bottle.png")
Ingredient.create(name: "cardboard", picture: "/ingredients/cardboard.png")
Ingredient.create(name: "ewaste", picture: "/ingredients/ewaste.png")
Ingredient.create(name: "food", picture: "/ingredients/food.png")
Ingredient.create(name: "plastic", picture: "/ingredients/plastic.png")
Ingredient.create(name: "waste", picture: "/ingredients/waste.png")