Item.create(name: "ball", size: 8, picture: "/items/ball.png")
Item.create(name: "bear", size: 8, picture: "/items/bear.png")
Item.create(name: "cube", size: 8, picture: "/items/cube.png")
Item.create(name: "egame", size: 8, picture: "/items/egame.png")
Item.create(name: "robot", size: 8, picture: "/items/robot.png")
Item.create(name: "xylophone", size: 8, picture: "/items/xylophone.png")